trigger: none # Only run this pipeline when manually triggered

parameters:
  - extends: ./params.yml
  - name: publishVersion
    displayName: Version to publish
    type: string
  - name: dryRun
    displayName: Dry run
    type: boolean
    default: false

resources:
  pipelines:
    - pipeline: build # This must be "build"
      source: \Azure Tools\VSCode\Extensions\vscode-containers # name of the pipeline that produces the artifacts
  repositories:
    - repository: azExtTemplates
      type: github
      name: microsoft/vscode-azuretools
      ref: bmw/pipelinesv2
      endpoint: GitHub-AzureTools # The service connection to use when accessing this repository

variables:
  # Required by MicroBuild template
  - name: TeamName
    value: "Container Tools Team"
  - template: azure-pipelines/v2/azcode.variables.yml@azExtTemplates

# Use those templates
extends:
  template: azure-pipelines/v2/1es-release-extension.yml@azExtTemplates
  parameters:
    publishVersion: ${{ parameters.publishVersion }}
    dryRun: ${{ parameters.dryRun }}
    extensionReleaseServiceConnection: ${{ variables.extensionReleaseServiceConnection }}
    packageToPublish: vscode-containers
    releasePool: ${{ parameters.releasePool }}
