trigger: none # Only run this pipeline when manually triggered

parameters:
  - name: publishVersion
    displayName: Version to publish
    type: string
  - name: dryRun
    displayName: Dry run
    type: boolean
    default: false

resources:
  repositories:
    - repository: azExtTemplates
      type: github
      name: microsoft/vscode-azuretools
      ref: bmw/pipelinesv2
      endpoint: GitHub-AzureTools # The service connection to use when accessing this repository

variables:
  # Required by MicroBuild template
  - name: TeamName
    value: "Container Tools Team"

# Use those templates
extends:
  template: azure-pipelines/v2/1es-release-extension.yml@azExtTemplates
  parameters:
    publishVersion: ${{ parameters.publishVersion }}
    dryRun: ${{ parameters.dryRun }}
    artifactPipeline: \Azure Tools\VSCode\Extensions\vscode-containers
