# Only run this pipeline when manually triggered
trigger: none
pr: none

parameters:
  # The version to publish--used for ensuring the expected version is published
  - name: publishVersion
    displayName: Version to publish
    type: string
  # Whether to do a dry run (i.e., not actually publish)
  - name: dryRun
    displayName: Dry run
    type: boolean
    default: false

resources:
  pipelines:
    # Reference the build pipeline to get the artifacts
    - pipeline: build # This must be "build"
      source: \Azure Tools\VSCode\Extensions\vscode-containers # Name of the pipeline that produces the artifacts
  repositories:
    # Use the shared templates from microsoft/vscode-azuretools
    - repository: azExtTemplates
      type: github
      name: microsoft/vscode-azuretools
      ref: bmw/pipelinesv2_2 # TODO: update to final branch
      endpoint: GitHub-AzureTools # The service connection to use when accessing this repository

variables:
  # Pick up shared AZCode variables
  - template: azdo-pipelines/azcode.variables.yml@azExtTemplates
  - name: TeamName
    value: "Container Tools Team" # Required by MicroBuild template

extends:
  template: azdo-pipelines/1es-mb-release-extension.yml@azExtTemplates # Use the extension release template
  parameters:
    packageToPublish: vscode-containers
    publishVersion: ${{ parameters.publishVersion }}
    dryRun: ${{ parameters.dryRun }}
    releaseServiceConnection: ${{ variables.extensionReleaseServiceConnection }}
    releaseApprovalEnvironment: VSCodeDockerExtensionPublish
